#!/bin/sh
ssh ec2-user@15.164.57.70 <<EOF	
    cd ~/aginginplace-web
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 21.6.2
    npm install
    npm install -g pm2
    pm2 restart ecosystem.config.js
    exit
EOF